// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package test1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Url                  *UrlVO   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	BizType              string   `protobuf:"bytes,13,opt,name=bizType,proto3" json:"bizType,omitempty"`
	RunMode              int32    `protobuf:"varint,14,opt,name=runMode,proto3" json:"runMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetUrl() *UrlVO {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *SearchRequest) GetBizType() string {
	if m != nil {
		return m.BizType
	}
	return ""
}

func (m *SearchRequest) GetRunMode() int32 {
	if m != nil {
		return m.RunMode
	}
	return 0
}

type UrlVO struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             string   `protobuf:"bytes,3,opt,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlVO) Reset()         { *m = UrlVO{} }
func (m *UrlVO) String() string { return proto.CompactTextString(m) }
func (*UrlVO) ProtoMessage()    {}
func (*UrlVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *UrlVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlVO.Unmarshal(m, b)
}
func (m *UrlVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlVO.Marshal(b, m, deterministic)
}
func (m *UrlVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlVO.Merge(m, src)
}
func (m *UrlVO) XXX_Size() int {
	return xxx_messageInfo_UrlVO.Size(m)
}
func (m *UrlVO) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlVO.DiscardUnknown(m)
}

var xxx_messageInfo_UrlVO proto.InternalMessageInfo

func (m *UrlVO) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UrlVO) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UrlVO) GetSnippets() string {
	if m != nil {
		return m.Snippets
	}
	return ""
}

type SearchResponse struct {
	RequestID            string   `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Jobs                 []string `protobuf:"bytes,4,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *SearchResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SearchResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SearchResponse) GetJobs() []string {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "test.SearchRequest")
	proto.RegisterType((*UrlVO)(nil), "test.UrlVO")
	proto.RegisterType((*SearchResponse)(nil), "test.SearchResponse")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xff, 0xfd, 0xb7, 0x9d, 0xeb, 0x9d, 0x1b, 0x72, 0xdd, 0x43, 0x18, 0x0a, 0xa5, 0x4f,
	0x7d, 0xea, 0xc3, 0xc4, 0x6f, 0x20, 0x82, 0x88, 0x08, 0x99, 0xfa, 0xbe, 0xd6, 0x8b, 0x56, 0x6a,
	0x1b, 0x73, 0xd3, 0x81, 0x7e, 0x7a, 0x49, 0xb2, 0x38, 0xf6, 0x96, 0xf3, 0x3b, 0xe1, 0xdc, 0xc3,
	0x81, 0x53, 0xa6, 0xad, 0x6e, 0xde, 0x2b, 0xa5, 0x07, 0x33, 0x60, 0x62, 0x88, 0x4d, 0x51, 0xc3,
	0x7c, 0xe3, 0xa8, 0xa4, 0xaf, 0x91, 0xd8, 0xe0, 0x25, 0xc4, 0xa3, 0xee, 0x44, 0x94, 0x47, 0xe5,
	0x6c, 0x3d, 0xab, 0xec, 0xa7, 0xea, 0x59, 0x77, 0x2f, 0x8f, 0xd2, 0x72, 0x14, 0x70, 0x52, 0xb7,
	0x3f, 0x4f, 0xdf, 0x8a, 0xc4, 0x3c, 0x8f, 0xca, 0x4c, 0x06, 0x69, 0x1d, 0x3d, 0xf6, 0x0f, 0xc3,
	0x2b, 0x89, 0x45, 0x1e, 0x95, 0xa9, 0x0c, 0xb2, 0xb8, 0x87, 0xd4, 0x25, 0xe0, 0xd9, 0x21, 0x3b,
	0xf3, 0x71, 0x4b, 0x48, 0x4d, 0x6b, 0x3a, 0x12, 0xff, 0x1d, 0xf3, 0x02, 0x57, 0x30, 0xe5, 0xbe,
	0x55, 0x8a, 0x0c, 0x8b, 0xd8, 0x19, 0x7f, 0xba, 0xd8, 0xc1, 0x22, 0x14, 0x66, 0x35, 0xf4, 0x4c,
	0x78, 0x01, 0x99, 0xf6, 0xe5, 0xef, 0x6e, 0xf6, 0xd9, 0x07, 0x60, 0x6b, 0xf1, 0xd8, 0x34, 0xc4,
	0xec, 0x6e, 0x4c, 0x65, 0x90, 0xd6, 0xf9, 0x24, 0xe6, 0xed, 0x1b, 0xed, 0x8f, 0x04, 0x89, 0x08,
	0xc9, 0xc7, 0x50, 0xb3, 0x48, 0xf2, 0xb8, 0xcc, 0xa4, 0x7b, 0xaf, 0x6f, 0xc3, 0x50, 0x1b, 0xd2,
	0xbb, 0xb6, 0x21, 0xbc, 0x86, 0x89, 0x07, 0x78, 0xee, 0x57, 0x3a, 0xda, 0x71, 0xb5, 0x3c, 0x86,
	0xbe, 0x6b, 0xf1, 0xaf, 0x9e, 0xb8, 0xf5, 0xaf, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x53, 0x37,
	0xf2, 0x01, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/test.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
